### ISSUE TITLE
flexGrid RowHeader Cell Template

### ISSUE THREAD

**Issue by enkaradag** [GrapeCity/ComponentOne-MAUI-Samples#2]
Hi,

Is it possible to set CellTemplate of **row header** in flexGrid?

One column of row header is automatically created at construction, so simply this piece of code should work;

```
datagrid.RowHeaderColumns[0].CellTemplate = new DataTemplate(() =>
        {
		Label l = new Label() { Text = "TEST" };
		return l;
        });
```
but nothing happens in row header. Am i missing something?

Regards

Ender

**Comment by arivoir** [comment]
CellTemplate is not supported in the row-headers column. but you can remove that column and add your own (Notice you'll lose editing and validation error icons).

**Comment by enkaradag** [comment]
Ok. did it that way. Thank you
